### ISSUE TITLE
'ltuthesis.cls' requires the file 'thumbs.sty'

### ISSUE THREAD

**Issue by Anas-Alhashimi** [rhostettler/ltuthesis#1]
Hello Roland,
I faced a problem while compiling the files.
The 'ltuthesis.cls' requires the file 'thumbs.sty' which i could not install correctly in my texmf TDS for unknown reason!

However, it works fine with old 'ltuthesis.cls' in master.

Thanks
/Anas

**Comment by rhostettler** [comment]
Hi Anas,

The 'thumbs' package can be obtained from CTAN, see [1].

Note, however, that the thumbmarks feature is still somewhat experimental and can be disabled by removing the 'thumbmarks' class option (which then doesn't require the thumbs package at all). I know that a few people have used thumbmarks successfully but it sometimes gives odd placement of the thumbmarks.

[1] https://www.ctan.org/tex-archive/macros/latex/contrib/thumbs
